---
title: "git_01"
author: "Lucille McEwen"
date: "September 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
All in the golden afternoon  
Full leisurely we glide;  
For both our oars, with little skill,  
By little arms are plied,  
While little hands make vain pretence  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
Who made the world?  
Who made the swan, and the black bear?  
Who made the grasshopper?  
This grasshopper, I mean-  
the one who has flung herself out of the grass,  
the one who is eating sugar out of my hand,  
who is moving her jaws back and forth instead of up and down-  
who is gazing around with her enormous and complicated eyes.  
Now she lifts her pale forearms and thoroughly washes her face.  
Now she snaps her wings open, and floats away.  
I don’t know exactly what a prayer is.  
I do know how to pay attention, how to fall down  
into the grass, how to kneel down in the grass,  
how to be idle and blessed, how to stroll through the fields,  
which is what I have been doing all day.  
Tell me, what else should I have done?  
Doesn’t everything die at last, and too soon?  
Tell me, what is it you plan to do  
with your one wild and precious life?  
  
-Mary Oliver